In [19]:
#normalization function data reading in 
import pandas as pd
import numpy as np

df = pd.io.parsers.read_csv(
    'https://raw.githubusercontent.com/rasbt/pattern_classification/master/data/wine_data.csv',
     header=None,
     usecols=[0,1,2]
    )

df.columns=['Class label', 'Alcohol', 'Malic acid']

df.head()

   Class label  Alcohol  Malic acid
0            1    14.23        1.71
1            1    13.20        1.78
2            1    13.16        2.36
3            1    14.37        1.95
4            1    13.24        2.59

In [21]:
#normalization function 
import pandas as pd
from sklearn import preprocessing


min_max_scaler = preprocessing.MinMaxScaler()
np_scaled = min_max_scaler.fit_transform(df[['Alcohol', 'Malic acid']])
df_normalized = pd.DataFrame(np_scaled)
df_normalized

            0         1
0    0.842105  0.191700
1    0.571053  0.205534
2    0.560526  0.320158
3    0.878947  0.239130
4    0.581579  0.365613
5    0.834211  0.201581
6    0.884211  0.223320
7    0.797368  0.278656
8    1.000000  0.177866
9    0.744737  0.120553
10   0.807895  0.280632
11   0.813158  0.146245
12   0.715789  0.195652
13   0.978947  0.195652
14   0.881579  0.223320
15   0.684211  0.211462
16   0.860526  0.233202
17   0.736842  0.164032
18   0.831579  0.167984
19   0.686842  0.466403
20   0.797368  0.175889
21   0.500000  0.604743
22   0.705263  0.221344
23   0.478947  0.169960
24   0.650000  0.211462
25   0.531579  0.258893
26   0.621053  0.203557
27   0.597368  0.193676
28   0.747368  0.229249
29   0.786842  0.185771
..        ...       ...
148  0.602632  0.494071
149  0.539474  0.624506
150  0.650000  0.470356
151  0.463158  0.381423
152  0.547368  0.229249
153  0.578947  0.505929
154  0.407895  0.108696
155  0.563158  0.879447
156  0.739474  0.667984
157  0.373684  0.452569
158  0.871053  0.185771
159  0.644737  0.183794
160  0.350000  0.610672
161  0.700000  0.498024
162  0.478947  0.500000
163  0.507895  0.535573
164  0.723684  0.399209
165  0.710526  0.715415
166  0.636842  0.584980
167  0.471053  0.519763
168  0.671053  0.363636
169  0.623684  0.762846
170  0.307895  0.452569
171  0.457895  0.326087
172  0.823684  0.349802
173  0.705263  0.970356
174  0.623684  0.626482
175  0.589474  0.699605
176  0.563158  0.365613
177  0.815789  0.664032

[178 rows x 2 columns]

In [22]:
# forward_selection function
import statsmodels.formula.api as smf

def forward_selected(data, response):
    """Linear model designed by forward selection.

    Parameters:
    -----------
    data : pandas DataFrame with all possible predictors and response

    response: string, name of response column in data

    Returns:
    --------
    model: an "optimal" fitted statsmodels linear model
           with an intercept
           selected by forward selection
           evaluated by adjusted R-squared
    """
    remaining = set(data.columns)
    remaining.remove(response)
    selected = []
    current_score, best_new_score = 0.0, 0.0
    while remaining and current_score == best_new_score:
        scores_with_candidates = []
        for candidate in remaining:
            formula = "{} ~ {} + 1".format(response,
                                           ' + '.join(selected + [candidate]))
            score = smf.ols(formula, data).fit().rsquared_adj
            scores_with_candidates.append((score, candidate))
        scores_with_candidates.sort()
        best_new_score, best_candidate = scores_with_candidates.pop()
        if current_score < best_new_score:
            remaining.remove(best_candidate)
            selected.append(best_candidate)
            current_score = best_new_score
    formula = "{} ~ {} + 1".format(response,
                                   ' + '.join(selected))
    model = smf.ols(formula, data).fit()
    return model

In [23]:
#forward selection 
import pandas as pd

url = "http://data.princeton.edu/wws509/datasets/salary.dat"
data = pd.read_csv(url, sep='\\s+')

model = forward_selected(data, 'sl')

print model.model.formula
# sl ~ rk + yr + 1

print model.rsquared_adj
# 0.835190760538

sl ~ rk + yr + 1
0.835190760538